name = "example-browser"

[defaults]
builder = "docker:generic"
runner = "local:docker"

[builders."docker:generic"]
enabled = true

[runners."local:docker"]
enabled = true

[[testcases]]
name = "success"
instances = { min = 1, max = 1, default = 1 }

  [testcases.params]
  browser = { type = "string", default = "chromium" }

[[testcases]]
name = "failure"
instances = { min = 1, max = 1, default = 1 }

  [testcases.params]
  browser = { type = "string", default = "chromium" }
