name: Testground Publish (edge)
on:
  push:
    branches:
      - master
  schedule:
    # we release the `edge` binary as an output artifact (see below).
    # Because these artifacts have a 90 days maximum retention period,
    # this cron makes sure we always have an `:edge` artifact available.
    - cron: "0 0 1 * *"

jobs:
  binaries:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.16.x"
        cache: true
    - name: Build Testground
      run: go build -ldflags "-X github.com/celestiaorg/testground/pkg/version.GitCommit=${GITHUB_SHA}" .
      shell: bash
    - uses: actions/upload-artifact@v3
      with:
        name: testground-release
        path: |
          ./testground
          ./static

  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    env:
        REGISTRY: ghcr.io
        IMAGE_NAME: ${{ github.repository }}
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: "${{ github.repository }}-testground:edge"
          file: ./Dockerfile.testground
          platforms: linux/arm64,linux/amd64
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: "${{ github.repository }}-sidecar:edge"
          file: ./Dockerfile.sidecar
          platforms: linux/arm64,linux/amd64
